{% set name = "fs.googledrivefs" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fs.googledrivefs-{{ version }}.tar.gz
  sha256: 751c163a577b58d3a349866657c904b501d4af4f5f20076c9e63906aa8a1cac9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.7
    - fs >=2.4.10
    - google-api-python-client >=1.6.3
    - google-auth >=1.5.1

test:
  imports:
    - fs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rkhwaja/fs.googledrivefs
  summary: Pyfilesystem2 implementation for Google Drive
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
