{% set name = "fs.googledrivefs" %}
{% set version = "2.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fs_googledrivefs-{{ version }}.tar.gz
  sha256: 7ccdb62f399624500224d5f6298e5ddb12c4657644cda5b98f9d4b3840324db4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - fs >=2.4.13
    - google-api-python-client >=1.7.10
    - google-auth >=1.5.1

test:
  imports:
    - fs
    - fs.googledrivefs
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/rkhwaja/fs.googledrivefs
  summary: Pyfilesystem2 implementation for Google Drive
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
